#!/usr/bin/env bash
# Runs the whole-SoC sign-off checks (simulation regression, lint,
# synthesis, STA) and collects the results into reports/sign_off/ as a
# single, committed snapshot -- so the final numbers (Fmax, area, which
# tests pass, lint findings) are readable straight from the repo without
# needing Verilator/Yosys/OpenSTA installed to regenerate them.
#
#   ./scripts/collect_soc_reports.sh
#
# Unlike the per-block logs under blocks/*/syn, blocks/*/sta, blocks/*/lint
# (gitignored -- regenerable scratch output), the files this script writes
# into reports/ ARE meant to be committed: they're the sign-off snapshot,
# not a build artifact.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/reports/sign_off"
mkdir -p "$OUT"

# Synthesis + STA need a Nangate45 liberty file, which can't be vendored
# into this repo (licensing) -- see TOOLCHAIN.md. Without NANGATE45_LIB
# set, skip those two steps gracefully instead of failing the whole run;
# regression/lint/coverage/dashboard don't need a PDK at all.
if [ -n "${NANGATE45_LIB:-}" ] && [ -f "${NANGATE45_LIB}" ]; then
  HAVE_PDK=1
else
  HAVE_PDK=0
  echo "NOTE: NANGATE45_LIB not set (or file missing) -- synthesis and STA" >&2
  echo "      will be SKIPPED. See TOOLCHAIN.md to set up the Nangate45 PDK." >&2
fi

echo "=== 1/6: full regression (scripts/run_regression.sh) ==="
"$ROOT/scripts/run_regression.sh" > "$OUT/simulation_regression.txt" 2>&1
regr_rc=$?
tail -25 "$OUT/simulation_regression.txt"

echo
echo "=== 2/6: lint (scripts/run_lint.sh) ==="
"$ROOT/scripts/run_lint.sh" > "$OUT/lint_summary.txt" 2>&1
lint_rc=$?
# run_lint.sh's soc_top entry uses absolute paths (needed so its
# multi-directory file list resolves regardless of cwd) -- strip the
# machine-local prefix before this lands in a committed report.
sed "s#$ROOT/##g" "$ROOT/blocks/soc_top/lint/lint_report.txt" > "$OUT/soc_top_lint_full.txt"
tail -20 "$OUT/lint_summary.txt"

echo
echo "=== 3/6: synthesis (blocks/soc_top/syn/synth.ys) ==="
SYNTH_FULL_LOG="$ROOT/blocks/soc_top/syn/synth_log.txt"
if [ "$HAVE_PDK" -eq 1 ]; then
  ( cd "$ROOT/blocks/soc_top/syn" && ./run_synth.sh > "$SYNTH_FULL_LOG" 2>&1 )
  synth_rc=$?
  # The full Yosys log runs into the tens of MB (every intermediate opt/
  # techmap pass over PicoRV32's hierarchy) -- not worth committing. Keep
  # just the final `stat` report (area/cell-count breakdown) here; the full
  # log stays local at blocks/soc_top/syn/synth_log.txt (gitignored).
  {
    echo "# Whole-SoC synthesis area report (Yosys, Nangate45)"
    echo "# Full verbose log (all optimization passes) kept locally at"
    echo "# blocks/soc_top/syn/synth_log.txt -- not committed (tens of MB)."
    echo
    tail -80 "$SYNTH_FULL_LOG"
  } > "$OUT/synthesis_area.txt"
else
  synth_rc=2
  echo "SKIPPED (no NANGATE45_LIB)" > "$OUT/synthesis_area.txt"
fi
tail -15 "$OUT/synthesis_area.txt"

# OpenSTA's simplified Verilog reader can't parse a few things Yosys's
# write_verilog emits (a `signed` keyword on post-synthesis nets, `(* ... *)`
# attribute lines, and a string parameter override on the boot_rom
# instance) -- none of it affects the netlist's actual function, so strip
# it before STA reads the file. See docs/performance.md's methodology note.
NETLIST="$ROOT/blocks/soc_top/syn/soc_top_out.v"
if [ -f "$NETLIST" ]; then
  sed -i.bak 's/wire signed/wire/g' "$NETLIST"
  sed -i.bak2 -E '/^[[:space:]]*\(\*.*\*\)[[:space:]]*$/d' "$NETLIST"
  python3 - "$NETLIST" <<'PYEOF'
import re, sys
path = sys.argv[1]
with open(path) as f:
    content = f.read()
pattern = re.compile(r'boot_rom #\(\s*\.HEXFILE\("firmware\.hex"\)\s*\)\s*u_rom \(')
content, _ = pattern.subn('boot_rom u_rom (', content)
with open(path, "w") as f:
    f.write(content)
PYEOF
  rm -f "$NETLIST.bak" "$NETLIST.bak2"
fi

echo
echo "=== 4/6: STA (blocks/soc_top/sta/sta.tcl) ==="
if [ "$HAVE_PDK" -eq 1 ]; then
  ( cd "$ROOT/blocks/soc_top/sta" && sta sta.tcl > "$OUT/timing_sta.txt" 2>&1 )
  sta_rc=$?
else
  sta_rc=2
  echo "SKIPPED (no NANGATE45_LIB)" > "$OUT/timing_sta.txt"
fi
tail -20 "$OUT/timing_sta.txt"

echo
echo "=== 5/6: coverage (scripts/run_coverage.sh + analyze_coverage.py) ==="
"$ROOT/scripts/run_coverage.sh" > "$OUT/coverage_run.txt" 2>&1
cov_rc=$?
tail -15 "$OUT/coverage_run.txt"
python3 "$ROOT/scripts/analyze_coverage.py"
analyze_rc=$?

echo
echo "=== 6/6: building the HTML dashboard (scripts/build_dashboard.py) ==="
python3 "$ROOT/scripts/build_dashboard.py"
dashboard_rc=$?

{
  echo "# soc_top sign-off report snapshot"
  echo
  echo "Generated by scripts/collect_soc_reports.sh on $(date '+%Y-%m-%d %H:%M %Z')."
  echo
  echo "| Check | Result | File |"
  echo "|---|---|---|"
  echo "| Simulation regression (19 targets) | $([ $regr_rc -eq 0 ] && echo PASS || echo FAIL) | \`simulation_regression.txt\` |"
  echo "| Lint (per-block, lint-only) | $([ $lint_rc -eq 0 ] && echo CLEAN || echo "warnings present") | \`lint_summary.txt\`, \`soc_top_lint_full.txt\` |"
  echo "| Synthesis (Yosys, Nangate45) | $([ $synth_rc -eq 0 ] && echo OK || ([ $synth_rc -eq 2 ] && echo "SKIPPED (no PDK)" || echo FAIL)) | \`synthesis_area.txt\` |"
  echo "| STA (OpenSTA) | $([ $sta_rc -eq 0 ] && echo OK || ([ $sta_rc -eq 2 ] && echo "SKIPPED (no PDK)" || echo FAIL)) | \`timing_sta.txt\` |"
  echo "| Coverage (line/toggle/branch/FSM) | $([ $cov_rc -eq 0 ] && echo OK || echo FAIL) | \`coverage/merged.dat\`, \`dashboard_data.json\` |"
  echo "| HTML dashboard | $([ $dashboard_rc -eq 0 ] && echo OK || echo FAIL) | \`dashboard.html\` (open directly in a browser) |"
  echo
  echo "See \`docs/performance.md\` and \`docs/verification_summary.md\` for the narrative writeup of these numbers."
} > "$OUT/README.md"

echo
echo "=== Reports collected into $OUT ==="
ls -la "$OUT"
